import clsx from "clsx"
import Head from "next/head"
import { data } from "data/data"
import CompanyList from "molecules/CompanyList/CompanyList"
import NavBar from "molecules/NavBar/NavBar"
import styles from "./Home.module.scss"

interface Props {
  className?: string
}

function Home({ className }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Construio - Find a Subcontractor Today</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <NavBar />
      </nav>

      <main className={styles.main}>
        <CompanyList data={data} />
      </main>

      <footer className={styles.footer}>Powered by NG</footer>
    </div>
  )
}

export default Home
